"""modified idx field max length in hanjin printwbls table

Revision ID: 020d8ae4699b
Revises: 64b945254dd5
Create Date: 2025-07-29 20:05:32.063617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020d8ae4699b'
down_revision: Union[str, None] = '64b945254dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hanjin_printwbls', 'idx',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_comment='주문번호',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hanjin_printwbls', 'idx',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_comment='주문번호',
               existing_nullable=True)
    # ### end Alembic commands ###
