"""fix mall_product_id cloumn unique in vlookup_datas table

Revision ID: 0307d29b029a
Revises: 96b5d9a4ebea
Create Date: 2025-08-30 21:09:41.826368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0307d29b029a'
down_revision: Union[str, None] = '96b5d9a4ebea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vlookup_datas', ['mall_product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vlookup_datas', type_='unique')
    # ### end Alembic commands ###
