"""0908a_order_erp_upload_sale_and_puchase

Revision ID: 066cb60a4ec4
Revises: 39ae956e7afc
Create Date: 2025-09-08 02:31:30.856293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '066cb60a4ec4'
down_revision: Union[str, None] = '39ae956e7afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecount_purchase',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('com_code', sa.String(length=6), nullable=False, comment='회사코드'),
    sa.Column('user_id', sa.String(length=30), nullable=False, comment='사용자ID'),
    sa.Column('emp_cd', sa.String(length=30), nullable=False, comment='담당자'),
    sa.Column('io_date', sa.String(length=8), nullable=True, comment='구매일자'),
    sa.Column('upload_ser_no', sa.Integer(), nullable=True, comment='순번'),
    sa.Column('cust', sa.String(length=30), nullable=True, comment='거래처코드'),
    sa.Column('cust_des', sa.String(length=50), nullable=True, comment='거래처명'),
    sa.Column('wh_cd', sa.Integer(), nullable=False, comment='입고창고'),
    sa.Column('io_type', sa.String(length=1), nullable=False, comment='거래유형'),
    sa.Column('exchange_type', sa.String(length=5), nullable=False, comment='통화'),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=4), nullable=True, comment='환율'),
    sa.Column('u_memo1', sa.String(length=100), nullable=True, comment='E-MAIL'),
    sa.Column('u_memo2', sa.String(length=100), nullable=True, comment='FAX'),
    sa.Column('u_memo3', sa.String(length=100), nullable=True, comment='연락처'),
    sa.Column('u_txt1', sa.String(length=100), nullable=True, comment='주소'),
    sa.Column('prod_cd', sa.String(length=20), nullable=False, comment='품목코드'),
    sa.Column('prod_des', sa.String(length=100), nullable=True, comment='품목명'),
    sa.Column('qty', sa.Numeric(precision=28, scale=10), nullable=False, comment='수량'),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=True, comment='단가'),
    sa.Column('exchange_cost', sa.Numeric(precision=28, scale=10), nullable=True, comment='외화금액'),
    sa.Column('supply_amt', sa.Numeric(precision=28, scale=4), nullable=True, comment='공급가액'),
    sa.Column('vat_amt', sa.Numeric(precision=28, scale=4), nullable=True, comment='부가세'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='적요'),
    sa.Column('is_success', sa.Boolean(), nullable=True, comment='성공여부'),
    sa.Column('slip_nos', sa.String(length=30), nullable=True, comment='구매번호(ERP)'),
    sa.Column('trace_id', sa.String(length=100), nullable=True, comment='로그확인용 일련번호'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류메시지'),
    sa.Column('is_test', sa.Boolean(), nullable=True, comment='테스트 여부'),
    sa.Column('work_status', sa.String(length=255), nullable=True, comment='작업상태'),
    sa.Column('batch_id', sa.String(length=255), nullable=True, comment='배치ID'),
    sa.Column('template_code', sa.String(length=255), nullable=True, comment='템플릿코드'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ecount_api_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='생성일시')
    op.alter_column('ecount_auth_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='생성일시')
    op.alter_column('ecount_auth_session', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='수정일시')
    op.alter_column('ecount_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='생성일시')
    op.alter_column('ecount_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='수정일시')
    op.add_column('ecount_erp_partner_code', sa.Column('fld_dsp', sa.String(length=255), nullable=True, comment='업체명'))
    op.add_column('ecount_erp_partner_code', sa.Column('wh_cd', sa.Integer(), nullable=True, comment='창고코드'))
    op.alter_column('ecount_erp_partner_code', 'partner_code',
               existing_type=sa.VARCHAR(length=255),
               comment='거래처 코드',
               existing_comment='파트너 코드',
               existing_nullable=True)
    op.alter_column('ecount_erp_partner_code', 'product_nm',
               existing_type=sa.VARCHAR(length=255),
               comment='품목코드',
               existing_comment='제품명',
               existing_nullable=True)
    op.add_column('ecount_iyes_cost', sa.Column('price', sa.Integer(), nullable=True, comment='원가(VAT 포함)'))
    op.add_column('ecount_iyes_cost', sa.Column('price_10_vat', sa.Integer(), nullable=True, comment='원가(VAT 10%)'))
    op.add_column('ecount_iyes_cost', sa.Column('price_20_vat', sa.Integer(), nullable=True, comment='원가(VAT 20%)'))
    op.drop_column('ecount_iyes_cost', 'cost_10_vat')
    op.drop_column('ecount_iyes_cost', 'cost_20_vat')
    op.drop_column('ecount_iyes_cost', 'cost')
    op.add_column('ecount_sale', sa.Column('emp_cd', sa.String(length=30), nullable=False, comment='담당자'))
    op.add_column('ecount_sale', sa.Column('io_type', sa.String(length=1), nullable=False, comment='거래유형'))
    op.add_column('ecount_sale', sa.Column('exchange_type', sa.String(length=5), nullable=False, comment='통화'))
    op.add_column('ecount_sale', sa.Column('exchange_rate', sa.Numeric(precision=18, scale=4), nullable=True, comment='환율'))
    op.add_column('ecount_sale', sa.Column('u_memo1', sa.String(length=100), nullable=True, comment='E-MAIL'))
    op.add_column('ecount_sale', sa.Column('u_memo2', sa.String(length=100), nullable=True, comment='FAX'))
    op.add_column('ecount_sale', sa.Column('u_memo3', sa.String(length=100), nullable=True, comment='연락처'))
    op.add_column('ecount_sale', sa.Column('u_txt1', sa.String(length=100), nullable=True, comment='주소'))
    op.add_column('ecount_sale', sa.Column('u_memo4', sa.String(length=100), nullable=True, comment='매장판매 결제구분(입금/현금/카드)'))
    op.add_column('ecount_sale', sa.Column('u_memo5', sa.String(length=100), nullable=True, comment='매장판매 거래구분(매장판매/매장구매)'))
    op.add_column('ecount_sale', sa.Column('exchange_cost', sa.Numeric(precision=28, scale=10), nullable=True, comment='외화금액'))
    op.add_column('ecount_sale', sa.Column('p_remarks2', sa.String(length=100), nullable=True, comment='배송메시지'))
    op.add_column('ecount_sale', sa.Column('p_remarks1', sa.String(length=100), nullable=True, comment='송장번호'))
    op.add_column('ecount_sale', sa.Column('p_remarks3', sa.String(length=100), nullable=True, comment='상품번호'))
    op.add_column('ecount_sale', sa.Column('size_des', sa.String(length=100), nullable=True, comment='주문번호'))
    op.add_column('ecount_sale', sa.Column('p_amt1', sa.Numeric(precision=28, scale=10), nullable=True, comment='정산예정금액'))
    op.add_column('ecount_sale', sa.Column('p_amt2', sa.Numeric(precision=28, scale=10), nullable=True, comment='서비스이용료'))
    op.add_column('ecount_sale', sa.Column('item_cd', sa.String(length=14), nullable=True, comment='운임비타입'))
    op.add_column('ecount_sale', sa.Column('slip_nos', sa.String(length=30), nullable=True, comment='판매번호(ERP)'))
    op.add_column('ecount_sale', sa.Column('work_status', sa.String(length=255), nullable=True, comment='작업상태'))
    op.add_column('ecount_sale', sa.Column('batch_id', sa.String(length=255), nullable=True, comment='배치ID'))
    op.add_column('ecount_sale', sa.Column('template_code', sa.String(length=255), nullable=True, comment='템플릿코드'))
    op.alter_column('ecount_sale', 'wh_cd',
               existing_type=sa.VARCHAR(length=5),
               comment='출하창고',
               existing_comment='출하창고코드',
               existing_nullable=False)
    op.alter_column('ecount_sale', 'remarks',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               comment='고객정보(이름/주문번호/연락처/주소/관리코드/장바구니번호',
               existing_comment='적요',
               existing_nullable=True)
    op.alter_column('ecount_sale', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='생성일시')
    op.alter_column('ecount_sale', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='수정일시')
    op.drop_column('ecount_sale', 'slip_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecount_sale', sa.Column('slip_no', sa.VARCHAR(length=30), autoincrement=False, nullable=True, comment='판매번호(ERP)'))
    op.alter_column('ecount_sale', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment='수정일시')
    op.alter_column('ecount_sale', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment='생성일시')
    op.alter_column('ecount_sale', 'remarks',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               comment='적요',
               existing_comment='고객정보(이름/주문번호/연락처/주소/관리코드/장바구니번호',
               existing_nullable=True)
    op.alter_column('ecount_sale', 'wh_cd',
               existing_type=sa.VARCHAR(length=5),
               comment='출하창고코드',
               existing_comment='출하창고',
               existing_nullable=False)
    op.drop_column('ecount_sale', 'template_code')
    op.drop_column('ecount_sale', 'batch_id')
    op.drop_column('ecount_sale', 'work_status')
    op.drop_column('ecount_sale', 'slip_nos')
    op.drop_column('ecount_sale', 'item_cd')
    op.drop_column('ecount_sale', 'p_amt2')
    op.drop_column('ecount_sale', 'p_amt1')
    op.drop_column('ecount_sale', 'size_des')
    op.drop_column('ecount_sale', 'p_remarks3')
    op.drop_column('ecount_sale', 'p_remarks1')
    op.drop_column('ecount_sale', 'p_remarks2')
    op.drop_column('ecount_sale', 'exchange_cost')
    op.drop_column('ecount_sale', 'u_memo5')
    op.drop_column('ecount_sale', 'u_memo4')
    op.drop_column('ecount_sale', 'u_txt1')
    op.drop_column('ecount_sale', 'u_memo3')
    op.drop_column('ecount_sale', 'u_memo2')
    op.drop_column('ecount_sale', 'u_memo1')
    op.drop_column('ecount_sale', 'exchange_rate')
    op.drop_column('ecount_sale', 'exchange_type')
    op.drop_column('ecount_sale', 'io_type')
    op.drop_column('ecount_sale', 'emp_cd')
    op.add_column('ecount_iyes_cost', sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True, comment='원가(VAT 포함)'))
    op.add_column('ecount_iyes_cost', sa.Column('cost_20_vat', sa.INTEGER(), autoincrement=False, nullable=True, comment='원가(VAT 20%)'))
    op.add_column('ecount_iyes_cost', sa.Column('cost_10_vat', sa.INTEGER(), autoincrement=False, nullable=True, comment='원가(VAT 10%)'))
    op.drop_column('ecount_iyes_cost', 'price_20_vat')
    op.drop_column('ecount_iyes_cost', 'price_10_vat')
    op.drop_column('ecount_iyes_cost', 'price')
    op.alter_column('ecount_erp_partner_code', 'product_nm',
               existing_type=sa.VARCHAR(length=255),
               comment='제품명',
               existing_comment='품목코드',
               existing_nullable=True)
    op.alter_column('ecount_erp_partner_code', 'partner_code',
               existing_type=sa.VARCHAR(length=255),
               comment='파트너 코드',
               existing_comment='거래처 코드',
               existing_nullable=True)
    op.drop_column('ecount_erp_partner_code', 'wh_cd')
    op.drop_column('ecount_erp_partner_code', 'fld_dsp')
    op.alter_column('ecount_config', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment='수정일시')
    op.alter_column('ecount_config', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment='생성일시')
    op.alter_column('ecount_auth_session', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment='수정일시')
    op.alter_column('ecount_auth_session', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment='생성일시')
    op.alter_column('ecount_api_log', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment='생성일시')
    op.drop_table('ecount_purchase')
    # ### end Alembic commands ###
