"""0928a_product_mall_value_table_added

Revision ID: 069694b2a301
Revises: a3e89236988d
Create Date: 2025-09-28 09:35:22.325849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069694b2a301'
down_revision: Union[str, None] = 'a3e89236988d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mall_info', sa.Column('mall_price_function', sa.String(length=255), nullable=True))
    op.add_column('mall_info', sa.Column('gubun', sa.String(length=255), nullable=True))
    op.add_column('mall_info', sa.Column('delivery_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mall_info', 'delivery_type')
    op.drop_column('mall_info', 'gubun')
    op.drop_column('mall_info', 'mall_price_function')
    # ### end Alembic commands ###
