"""feat_test_down_form_orders_added_others_data_type_modified

Revision ID: 14dfd6f0274d
Revises: 8deb89464864
Create Date: 2025-07-25 13:16:38.536432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dfd6f0274d'
down_revision: Union[str, None] = '8deb89464864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
