"""1001a_product_mall_value_convert_shops_to_jsonb

Revision ID: 174dace22f4e
Revises: 69b6a0e0501b
Create Date: 2025-10-01 23:49:46.471441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '174dace22f4e'
down_revision: Union[str, None] = '69b6a0e0501b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_mall_value', sa.Column('shops', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    op.drop_column('product_mall_value', 'shop0381')
    op.drop_column('product_mall_value', 'shop0273')
    op.drop_column('product_mall_value', 'shop0042')
    op.drop_column('product_mall_value', 'shop0094')
    op.drop_column('product_mall_value', 'shop0661')
    op.drop_column('product_mall_value', 'shop0464')
    op.drop_column('product_mall_value', 'shop0650')
    op.drop_column('product_mall_value', 'shop0100')
    op.drop_column('product_mall_value', 'shop0067')
    op.drop_column('product_mall_value', 'shop0007')
    op.drop_column('product_mall_value', 'shop0416')
    op.drop_column('product_mall_value', 'shop0387')
    op.drop_column('product_mall_value', 'shop0129')
    op.drop_column('product_mall_value', 'shop0121')
    op.drop_column('product_mall_value', 'shop0666')
    op.drop_column('product_mall_value', 'shop0154')
    op.drop_column('product_mall_value', 'shop0298')
    op.drop_column('product_mall_value', 'shop0372')
    op.drop_column('product_mall_value', 'shop0449')
    op.drop_column('product_mall_value', 'shop0444')
    op.drop_column('product_mall_value', 'shop0498')
    op.drop_column('product_mall_value', 'shop0365')
    op.drop_column('product_mall_value', 'shop0055')
    op.drop_column('product_mall_value', 'shop0322')
    op.drop_column('product_mall_value', 'shop0587')
    op.drop_column('product_mall_value', 'shop0319')
    op.drop_column('product_mall_value', 'shop0075')
    op.drop_column('product_mall_value', 'shop0068')
    op.drop_column('product_mall_value', 'shop0189')
    op.drop_column('product_mall_value', 'shop0087')
    op.drop_column('product_mall_value', 'shop0029')
    op.drop_column('product_mall_value', 'shop0583')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_mall_value', sa.Column('shop0583', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0029', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0087', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0189', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0068', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0075', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0319', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0587', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0322', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0055', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0365', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0498', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0444', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0449', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0372', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0298', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0154', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0666', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0121', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0129', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0387', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0416', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0007', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0067', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0100', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0650', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0464', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0661', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0094', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0042', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0273', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_mall_value', sa.Column('shop0381', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product_mall_value', 'shops')
    # ### end Alembic commands ###
