"""0903a_down_form_order_excel_up_download_develop

Revision ID: 1d0bb2e39854
Revises: 0307d29b029a
Create Date: 2025-09-03 06:39:43.727224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0bb2e39854'
down_revision: Union[str, None] = '0307d29b029a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('down_form_orders', 'delivery_payment_type')
    op.drop_column('test_down_form_orders', 'delivery_payment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_down_form_orders', sa.Column('delivery_payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('down_form_orders', sa.Column('delivery_payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
