"""0914a_order_down_form_orders_work_status_length_increased

Revision ID: 20182838e5e0
Revises: bd10cae64be5
Create Date: 2025-09-14 22:09:32.018559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20182838e5e0'
down_revision: Union[str, None] = 'bd10cae64be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('down_form_orders', 'work_status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('test_down_form_orders', 'work_status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_down_form_orders', 'work_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=14),
               existing_nullable=True)
    op.alter_column('down_form_orders', 'work_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=14),
               existing_nullable=True)
    # ### end Alembic commands ###
