"""0728A_added_hanjin_orders_and_printwbls

Revision ID: 34f827b98359
Revises: 14dfd6f0274d
Create Date: 2025-07-28 02:24:12.632770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34f827b98359'
down_revision: Union[str, None] = '14dfd6f0274d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hanjin_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_edi_cd', sa.String(length=50), nullable=True, comment='EDI코드'),
    sa.Column('cust_ord_no', sa.String(length=100), nullable=True, comment='주문번호'),
    sa.Column('wbl_no', sa.String(length=50), nullable=True, comment='운송장번호'),
    sa.Column('svc_cat_cd', sa.String(length=1), nullable=True, comment='배송구분(S:출고, F:포커스, E:직택배, R:반품)'),
    sa.Column('contract_no', sa.String(length=50), nullable=True, comment='계약번호'),
    sa.Column('pickup_ask_dt', sa.String(length=8), nullable=True, comment='주문 전송일(YYYYMMDD)'),
    sa.Column('sndr_zip', sa.String(length=10), nullable=True, comment='송하인 우편번호'),
    sa.Column('sndr_base_addr', sa.String(length=500), nullable=True, comment='송하인 주소1'),
    sa.Column('sndr_dtl_addr', sa.String(length=500), nullable=True, comment='송하인 주소2'),
    sa.Column('sndr_nm', sa.String(length=100), nullable=True, comment='송하인명'),
    sa.Column('sndr_tel_no', sa.String(length=20), nullable=True, comment='송하인 전화번호'),
    sa.Column('sndr_mobile_no', sa.String(length=20), nullable=True, comment='송하인 핸드폰번호'),
    sa.Column('sndr_ask_content', sa.Text(), nullable=True, comment='송하인 배송메시지'),
    sa.Column('sndr_ref_content', sa.String(length=100), nullable=True, comment='송하인 담당자명'),
    sa.Column('rcvr_zip', sa.String(length=10), nullable=True, comment='수하인 우편번호'),
    sa.Column('rcvr_base_addr', sa.String(length=500), nullable=True, comment='수하인 주소1'),
    sa.Column('rcvr_dtl_addr', sa.String(length=500), nullable=True, comment='수하인 주소2'),
    sa.Column('rcvr_nm', sa.String(length=100), nullable=True, comment='수하인명'),
    sa.Column('rcvr_tel_no', sa.String(length=20), nullable=True, comment='수하인 전화번호'),
    sa.Column('rcvr_mobile_no', sa.String(length=20), nullable=True, comment='수하인 핸드폰번호'),
    sa.Column('rcvr_ask_content', sa.Text(), nullable=True, comment='수하인 배송메시지'),
    sa.Column('rcvr_ref_content', sa.String(length=100), nullable=True, comment='수하인 담당자명'),
    sa.Column('commodity_nm', sa.String(length=200), nullable=True, comment='상품명'),
    sa.Column('pay_typ_cd', sa.String(length=2), nullable=True, comment='지불조건 CD(발지신용), CT(착지신용), PP(선불), CC(착불)'),
    sa.Column('box_typ_cd', sa.String(length=1), nullable=True, comment='박스타입(S,A,B,C,D,E)'),
    sa.Column('print_memo1', sa.String(length=500), nullable=True, comment='메모1'),
    sa.Column('print_memo2', sa.String(length=500), nullable=True, comment='메모2'),
    sa.Column('print_memo3', sa.String(length=500), nullable=True, comment='메모3'),
    sa.Column('print_memo4', sa.String(length=500), nullable=True, comment='메모4'),
    sa.Column('commodity_list', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='상품리스트'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='주문상태'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_ord_no')
    )
    op.create_index(op.f('ix_hanjin_orders_id'), 'hanjin_orders', ['id'], unique=False)
    op.create_table('hanjin_printwbls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='기본키'),
    sa.Column('idx', sa.String(length=50), nullable=True, comment='주문번호'),
    sa.Column('msg_key', sa.String(length=100), nullable=True, comment='메세지KEY - 자료 매칭을 위한 고객사 고유키'),
    sa.Column('result_code', sa.String(length=10), nullable=True, comment='결과코드'),
    sa.Column('result_message', sa.String(length=200), nullable=True, comment='결과메세지'),
    sa.Column('s_tml_nam', sa.String(length=100), nullable=True, comment='집하지 터미널명'),
    sa.Column('s_tml_cod', sa.String(length=10), nullable=True, comment='집하지 터미널코드'),
    sa.Column('zip_cod', sa.String(length=10), nullable=True, comment='정제된 우편번호'),
    sa.Column('tml_nam', sa.String(length=100), nullable=True, comment='도착지 터미널명'),
    sa.Column('tml_cod', sa.String(length=10), nullable=True, comment='도착지 터미널코드'),
    sa.Column('cen_nam', sa.String(length=100), nullable=True, comment='도착지 집배점명'),
    sa.Column('cen_cod', sa.String(length=10), nullable=True, comment='도착지 집배점코드'),
    sa.Column('pd_tim', sa.String(length=10), nullable=True, comment='집배소요시간'),
    sa.Column('dom_rgn', sa.String(length=10), nullable=True, comment='권역구분'),
    sa.Column('hub_cod', sa.String(length=10), nullable=True, comment='허브코드'),
    sa.Column('dom_mid', sa.String(length=10), nullable=True, comment='중분류코드'),
    sa.Column('es_cod', sa.String(length=10), nullable=True, comment='배송사원분류코드'),
    sa.Column('grp_rnk', sa.String(length=10), nullable=True, comment='소분류코드'),
    sa.Column('es_nam', sa.String(length=100), nullable=True, comment='배송사원명'),
    sa.Column('prt_add', sa.Text(), nullable=True, comment='주소 출력정보'),
    sa.Column('wbl_num', sa.String(length=50), nullable=True, comment='운송장번호'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='수정일시'),
    sa.Column('snd_zip', sa.String(length=10), nullable=True, comment='출발지 우편번호'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('batch_process', 'date_from',
               existing_type=postgresql.TIMESTAMP(),
               comment='주문 시작 일자',
               existing_comment='배치 프로세스 시작 일자',
               existing_nullable=True)
    op.alter_column('batch_process', 'date_to',
               existing_type=postgresql.TIMESTAMP(),
               comment='주문 종료 일자',
               existing_comment='배치 프로세스 종료 일자',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch_process', 'date_to',
               existing_type=postgresql.TIMESTAMP(),
               comment='배치 프로세스 종료 일자',
               existing_comment='주문 종료 일자',
               existing_nullable=True)
    op.alter_column('batch_process', 'date_from',
               existing_type=postgresql.TIMESTAMP(),
               comment='배치 프로세스 시작 일자',
               existing_comment='주문 시작 일자',
               existing_nullable=True)
    op.drop_table('hanjin_printwbls')
    op.drop_index(op.f('ix_hanjin_orders_id'), table_name='hanjin_orders')
    op.drop_table('hanjin_orders')
    # ### end Alembic commands ###
