"""0907a_order_erp_partner_code_and_iyes_cost

Revision ID: 39ae956e7afc
Revises: 1d0bb2e39854
Create Date: 2025-09-07 17:51:33.641340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ae956e7afc'
down_revision: Union[str, None] = '1d0bb2e39854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecount_api_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('com_code', sa.String(length=6), nullable=False, comment='회사코드'),
    sa.Column('user_id', sa.String(length=30), nullable=False, comment='사용자ID'),
    sa.Column('api_type', sa.String(length=20), nullable=False, comment='API 유형 (zone, login, sale)'),
    sa.Column('api_url', sa.String(length=500), nullable=False, comment='API URL'),
    sa.Column('request_method', sa.String(length=10), nullable=True, comment='요청 메소드'),
    sa.Column('request_headers', sa.Text(), nullable=True, comment='요청 헤더'),
    sa.Column('request_body', sa.Text(), nullable=True, comment='요청 본문'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='응답 상태코드'),
    sa.Column('response_headers', sa.Text(), nullable=True, comment='응답 헤더'),
    sa.Column('response_body', sa.Text(), nullable=True, comment='응답 본문'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='응답시간(밀리초)'),
    sa.Column('is_success', sa.Boolean(), nullable=True, comment='성공여부'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류메시지'),
    sa.Column('is_test', sa.Boolean(), nullable=True, comment='테스트 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecount_auth_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('com_code', sa.String(length=6), nullable=False, comment='회사코드'),
    sa.Column('user_id', sa.String(length=30), nullable=False, comment='사용자ID'),
    sa.Column('zone', sa.String(length=2), nullable=False, comment='Zone 정보'),
    sa.Column('domain', sa.String(length=30), nullable=False, comment='도메인 정보'),
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='세션ID'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성 여부'),
    sa.Column('is_test', sa.Boolean(), nullable=True, comment='테스트 여부'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='만료일시'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecount_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='설정 키'),
    sa.Column('config_value', sa.Text(), nullable=True, comment='설정 값'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='설명'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('ecount_erp_partner_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_code', sa.String(length=255), nullable=True, comment='파트너 코드'),
    sa.Column('product_nm', sa.String(length=255), nullable=True, comment='제품명'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecount_erp_partner_code_id'), 'ecount_erp_partner_code', ['id'], unique=False)
    op.create_table('ecount_iyes_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_nm', sa.String(length=255), nullable=True, comment='제품명'),
    sa.Column('cost', sa.Integer(), nullable=True, comment='원가(VAT 포함)'),
    sa.Column('cost_10_vat', sa.Integer(), nullable=True, comment='원가(VAT 10%)'),
    sa.Column('cost_20_vat', sa.Integer(), nullable=True, comment='원가(VAT 20%)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecount_iyes_cost_id'), 'ecount_iyes_cost', ['id'], unique=False)
    op.create_table('ecount_sale',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('com_code', sa.String(length=6), nullable=False, comment='회사코드'),
    sa.Column('user_id', sa.String(length=30), nullable=False, comment='사용자ID'),
    sa.Column('upload_ser_no', sa.Integer(), nullable=True, comment='순번'),
    sa.Column('io_date', sa.String(length=8), nullable=True, comment='판매일자'),
    sa.Column('cust', sa.String(length=30), nullable=True, comment='거래처코드'),
    sa.Column('cust_des', sa.String(length=50), nullable=True, comment='거래처명'),
    sa.Column('wh_cd', sa.Integer(), nullable=False, comment='출하창고코드'),
    sa.Column('prod_cd', sa.String(length=20), nullable=False, comment='품목코드'),
    sa.Column('prod_des', sa.String(length=100), nullable=True, comment='품목명'),
    sa.Column('qty', sa.Numeric(precision=28, scale=10), nullable=False, comment='수량'),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=True, comment='단가'),
    sa.Column('supply_amt', sa.Numeric(precision=28, scale=4), nullable=True, comment='공급가액'),
    sa.Column('vat_amt', sa.Numeric(precision=28, scale=4), nullable=True, comment='부가세'),
    sa.Column('remarks', sa.String(length=200), nullable=True, comment='적요'),
    sa.Column('is_success', sa.Boolean(), nullable=True, comment='성공여부'),
    sa.Column('slip_no', sa.String(length=30), nullable=True, comment='판매번호(ERP)'),
    sa.Column('trace_id', sa.String(length=100), nullable=True, comment='로그확인용 일련번호'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류메시지'),
    sa.Column('is_test', sa.Boolean(), nullable=True, comment='테스트 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecount_sale')
    op.drop_index(op.f('ix_ecount_iyes_cost_id'), table_name='ecount_iyes_cost')
    op.drop_table('ecount_iyes_cost')
    op.drop_index(op.f('ix_ecount_erp_partner_code_id'), table_name='ecount_erp_partner_code')
    op.drop_table('ecount_erp_partner_code')
    op.drop_table('ecount_config')
    op.drop_table('ecount_auth_session')
    op.drop_table('ecount_api_log')
    # ### end Alembic commands ###
