"""0731a_test_product_raw_data_null_handling

Revision ID: 4f5aae2f5147
Revises: c2a302d10370
Create Date: 2025-08-01 09:08:15.933378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5aae2f5147'
down_revision: Union[str, None] = 'c2a302d10370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_registration_raw_data', sa.Column('stock_use_yn', sa.String(length=1), nullable=True, comment='재고관리사용여부'))
    op.alter_column('test_product_raw_data', 'class_cd1',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('test_product_raw_data', 'class_cd2',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('test_product_raw_data', 'class_cd3',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('test_product_raw_data', 'gubun',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('test_product_raw_data', 'origin',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('test_product_raw_data', 'goods_season',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('test_product_raw_data', 'sex',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('test_product_raw_data', 'status',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('test_product_raw_data', 'tax_yn',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('test_product_raw_data', 'delv_type',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('test_product_raw_data', 'goods_price',
               existing_type=sa.NUMERIC(precision=12, scale=0),
               nullable=True)
    op.alter_column('test_product_raw_data', 'goods_consumer_price',
               existing_type=sa.NUMERIC(precision=12, scale=0),
               nullable=True)
    op.alter_column('test_product_raw_data', 'img_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('test_product_raw_data', 'opt_type',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text('2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_product_raw_data', 'opt_type',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.alter_column('test_product_raw_data', 'img_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('test_product_raw_data', 'goods_consumer_price',
               existing_type=sa.NUMERIC(precision=12, scale=0),
               nullable=False)
    op.alter_column('test_product_raw_data', 'goods_price',
               existing_type=sa.NUMERIC(precision=12, scale=0),
               nullable=False)
    op.alter_column('test_product_raw_data', 'delv_type',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('test_product_raw_data', 'tax_yn',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('test_product_raw_data', 'status',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('test_product_raw_data', 'sex',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('test_product_raw_data', 'goods_season',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('test_product_raw_data', 'origin',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('test_product_raw_data', 'gubun',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('test_product_raw_data', 'class_cd3',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('test_product_raw_data', 'class_cd2',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('test_product_raw_data', 'class_cd1',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('product_registration_raw_data', 'stock_use_yn')
    # ### end Alembic commands ###
