"""0730a_added_smile_db

Revision ID: 6255c323ba14
Revises: 020d8ae4699b
Create Date: 2025-07-30 13:03:27.663327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6255c323ba14'
down_revision: Union[str, None] = '020d8ae4699b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smile_erp_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True, comment='날짜'),
    sa.Column('site', sa.String(length=50), nullable=True, comment='사이트'),
    sa.Column('customer_name', sa.String(length=100), nullable=True, comment='고객성함'),
    sa.Column('order_number', sa.String(length=100), nullable=True, comment='주문번호'),
    sa.Column('erp_code', sa.String(length=100), nullable=True, comment='ERP'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smile_settlement_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=True, comment='주문번호'),
    sa.Column('product_number', sa.String(length=100), nullable=True, comment='상품번호'),
    sa.Column('cart_number', sa.String(length=100), nullable=True, comment='장바구니번호'),
    sa.Column('product_name', sa.String(length=200), nullable=True, comment='상품명'),
    sa.Column('buyer_name', sa.String(length=100), nullable=True, comment='구매자명'),
    sa.Column('payment_confirmation_date', sa.Date(), nullable=True, comment='입금확인일'),
    sa.Column('delivery_completion_date', sa.Date(), nullable=True, comment='배송완료일'),
    sa.Column('early_settlement_date', sa.Date(), nullable=True, comment='조기정산일자'),
    sa.Column('settlement_type', sa.String(length=50), nullable=True, comment='구분'),
    sa.Column('sales_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='판매금액'),
    sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='서비스이용료'),
    sa.Column('settlement_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='정산금액'),
    sa.Column('transfer_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='송금대상액'),
    sa.Column('payment_date', sa.Date(), nullable=True, comment='결제일'),
    sa.Column('shipping_date', sa.Date(), nullable=True, comment='발송일'),
    sa.Column('refund_date', sa.Date(), nullable=True, comment='환불일'),
    sa.Column('site', sa.String(length=50), nullable=True, comment='사이트'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smile_sku_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_number', sa.String(length=100), nullable=True, comment='SKU번호'),
    sa.Column('model_name', sa.String(length=200), nullable=True, comment='모델명'),
    sa.Column('sku_name', sa.String(length=200), nullable=True, comment='SKU명'),
    sa.Column('comment', sa.Text(), nullable=True, comment='comment'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smile_sku_data')
    op.drop_table('smile_settlement_data')
    op.drop_table('smile_erp_data')
    # ### end Alembic commands ###
