"""0811a_product_prop_edit_yn_added

Revision ID: 660deadf95ff
Revises: 4f5aae2f5147
Create Date: 2025-08-11 03:56:42.632204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660deadf95ff'
down_revision: Union[str, None] = '4f5aae2f5147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_product_raw_data', sa.Column('prop_edit_yn', sa.CHAR(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_product_raw_data', 'prop_edit_yn')
    # ### end Alembic commands ###
