"""0915a_order_Fix io_type field length in ecount_sale table

Revision ID: 67f805bc3215
Revises: 20182838e5e0
Create Date: 2025-09-15 01:12:06.215402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f805bc3215'
down_revision: Union[str, None] = '20182838e5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecount_purchase', 'io_type',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_comment='거래유형',
               existing_nullable=False)
    op.alter_column('ecount_sale', 'io_type',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_comment='거래유형',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecount_sale', 'io_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               existing_comment='거래유형',
               existing_nullable=False)
    op.alter_column('ecount_purchase', 'io_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               existing_comment='거래유형',
               existing_nullable=False)
    # ### end Alembic commands ###
