"""0928c_product_mall_value_shop0666_added

Revision ID: 69b6a0e0501b
Revises: f7a6426e65ad
Create Date: 2025-09-28 23:47:24.003004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b6a0e0501b'
down_revision: Union[str, None] = 'f7a6426e65ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_mall_value', sa.Column('shop0666', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_mall_value', 'shop0666')
    # ### end Alembic commands ###
