"""0729a_added_macro_match_by_file_name

Revision ID: 781b8d496be1
Revises: 9e677d90a65b
Create Date: 2025-07-29 01:08:11.712577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781b8d496be1'
down_revision: Union[str, None] = '9e677d90a65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_templates', sa.Column('site_type', sa.String(length=20), nullable=True, comment='template 구분. 구분자 -- , -- [G마켓,옥션], [기본양식], [브랜디]'))
    op.add_column('export_templates', sa.Column('usage_type', sa.String(length=20), nullable=True, comment='template 구분. 구분자 -- , -- ERP용, 합포장용'))
    op.add_column('export_templates', sa.Column('is_star', sa.Boolean(), server_default='false', nullable=True, comment='스타배송 여부'))
    op.alter_column('export_templates', 'template_name',
               existing_type=sa.VARCHAR(length=100),
               comment='표시용 이름',
               existing_nullable=False)
    op.add_column('macro_info', sa.Column('sub_site', sa.String(length=20), nullable=True, comment='macro 구분 -- 알리, 지그재그, 기타사이트'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('macro_info', 'sub_site')
    op.alter_column('export_templates', 'template_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='표시용 이름',
               existing_nullable=False)
    op.drop_column('export_templates', 'is_star')
    op.drop_column('export_templates', 'usage_type')
    op.drop_column('export_templates', 'site_type')
    # ### end Alembic commands ###
