"""0821a_down_form_order_batch_id_added

Revision ID: 7c1167c5080e
Revises: f35a4bad392d
Create Date: 2025-08-21 04:55:06.476160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1167c5080e'
down_revision: Union[str, None] = 'f35a4bad392d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('down_form_orders', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.add_column('test_down_form_orders', sa.Column('batch_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_down_form_orders', 'batch_id')
    op.drop_column('down_form_orders', 'batch_id')
    # ### end Alembic commands ###
