"""create vlooup_data tabel

Revision ID: 96b5d9a4ebea
Revises: b773230094af
Create Date: 2025-08-28 14:29:40.142449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b5d9a4ebea'
down_revision: Union[str, None] = 'b773230094af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vlookup_datas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mall_product_id', sa.Text(), nullable=True),
    sa.Column('delv_cost', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vlookup_datas')
    # ### end Alembic commands ###
