"""0821a_increase_work_status_field_length_to_100

Revision ID: 9974cd4a0062
Revises: 7c1167c5080e
Create Date: 2025-08-21 14:40:06.272466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9974cd4a0062'
down_revision: Union[str, None] = '7c1167c5080e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch_process', 'work_status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=100),
               existing_comment='작업 상태',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch_process', 'work_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=14),
               existing_comment='작업 상태',
               existing_nullable=True)
    # ### end Alembic commands ###
