"""0908b_order_erp_upload_sale_and_purchase

Revision ID: a31b8d3efed2
Revises: 066cb60a4ec4
Create Date: 2025-09-08 03:07:22.640033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31b8d3efed2'
down_revision: Union[str, None] = '066cb60a4ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE ecount_purchase ALTER COLUMN wh_cd TYPE INTEGER USING wh_cd::integer")
    op.execute("ALTER TABLE ecount_sale ALTER COLUMN wh_cd TYPE INTEGER USING wh_cd::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecount_sale', 'wh_cd',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5),
               existing_comment='출하창고',
               existing_nullable=False)
    op.alter_column('ecount_purchase', 'wh_cd',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5),
               existing_comment='입고창고',
               existing_nullable=False)
    # ### end Alembic commands ###
