"""0922a_product_one_plus_one_product_registration_update

Revision ID: a3e89236988d
Revises: 67f805bc3215
Create Date: 2025-09-22 06:37:49.866004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e89236988d'
down_revision: Union[str, None] = '67f805bc3215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_registration_raw_data', sa.Column('char_1_val_one_plus', sa.Text(), nullable=True, comment='1+1옵션(1단)'))
    op.add_column('product_registration_raw_data', sa.Column('char_2_val_one_plus', sa.Text(), nullable=True, comment='1+1옵션(22단)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_registration_raw_data', 'char_2_val_one_plus')
    op.drop_column('product_registration_raw_data', 'char_1_val_one_plus')
    # ### end Alembic commands ###
