"""0823a_smile_macro_reg_date_batch_id_added

Revision ID: b693593305e6
Revises: c26b8500c811
Create Date: 2025-08-23 10:39:58.303895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b693593305e6'
down_revision: Union[str, None] = 'c26b8500c811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smile_macro', sa.Column('reg_date', sa.String(length=14), nullable=True, comment='수집일자'))
    op.add_column('smile_macro', sa.Column('batch_id', sa.Integer(), nullable=True, comment='배치 프로세스 ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smile_macro', 'batch_id')
    op.drop_column('smile_macro', 'reg_date')
    # ### end Alembic commands ###
