"""0819a_smile_smile_macro_added

Revision ID: bc201165454f
Revises: 660deadf95ff
Create Date: 2025-08-19 04:36:28.363324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc201165454f'
down_revision: Union[str, None] = '660deadf95ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smile_macro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fld_dsp', sa.String(length=100), nullable=False, comment='아이디*'),
    sa.Column('expected_payout', sa.Numeric(precision=15, scale=2), nullable=True, comment='정산예정금??'),
    sa.Column('service_fee', sa.Numeric(precision=15, scale=2), nullable=True, comment='서비스 이용료'),
    sa.Column('mall_order_id', sa.String(length=100), nullable=True, comment='장바구니번호(결제번호)'),
    sa.Column('pay_cost', sa.Numeric(precision=15, scale=2), nullable=True, comment='금액[배송비미포함]'),
    sa.Column('delv_cost', sa.Numeric(precision=15, scale=2), nullable=True, comment='배송비 금액'),
    sa.Column('mall_product_id', sa.String(length=100), nullable=True, comment='상품번호*'),
    sa.Column('order_id', sa.String(length=100), nullable=True, comment='주문번호*'),
    sa.Column('chat_1', sa.String(length=200), nullable=True, comment='주문옵션'),
    sa.Column('product_name', sa.String(length=500), nullable=True, comment='상품명'),
    sa.Column('item_name', sa.String(length=500), nullable=True, comment='제품명'),
    sa.Column('sale_cnt', sa.Integer(), nullable=True, comment='수량'),
    sa.Column('sale_cost', sa.Numeric(precision=15, scale=2), nullable=True, comment='판매금액'),
    sa.Column('mall_user_id', sa.String(length=100), nullable=True, comment='구매자ID'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='구매자명'),
    sa.Column('receive_name', sa.String(length=100), nullable=True, comment='수령인명'),
    sa.Column('delivery_method_str', sa.String(length=50), nullable=True, comment='배송비'),
    sa.Column('receive_cel', sa.String(length=20), nullable=True, comment='수령인 휴대폰'),
    sa.Column('receive_tel', sa.String(length=20), nullable=True, comment='수령인 전화번호'),
    sa.Column('receive_addr', sa.Text(), nullable=True, comment='주소'),
    sa.Column('receive_zipcode', sa.String(length=10), nullable=True, comment='우편번호'),
    sa.Column('delv_msg', sa.Text(), nullable=True, comment='배송시 요구사항'),
    sa.Column('sku1_num', sa.String(length=100), nullable=True, comment='SKU1번호'),
    sa.Column('sku1_cnt', sa.String(length=50), nullable=True, comment='SKU1수량'),
    sa.Column('sku2_num', sa.String(length=100), nullable=True, comment='SKU2번호'),
    sa.Column('sku2_cnt', sa.String(length=50), nullable=True, comment='SKU2수량'),
    sa.Column('sku_num', sa.String(length=200), nullable=True, comment='SKU번호 및 수량'),
    sa.Column('pay_dt', sa.Date(), nullable=True, comment='결제완료일'),
    sa.Column('user_tel', sa.String(length=20), nullable=True, comment='구매자 전화번호'),
    sa.Column('user_cel', sa.String(length=20), nullable=True, comment='구매자 휴대폰'),
    sa.Column('buy_coupon', sa.Numeric(precision=15, scale=2), nullable=True, comment='구매쿠폰적용금액'),
    sa.Column('delv_id', sa.String(length=100), nullable=True, comment='배송번호'),
    sa.Column('delv_status', sa.String(length=50), nullable=True, comment='배송상태'),
    sa.Column('order_dt', sa.Date(), nullable=True, comment='주문일자(결제확인전)'),
    sa.Column('order_method', sa.String(length=50), nullable=True, comment='주문종류'),
    sa.Column('delv_method_id', sa.String(length=100), nullable=True, comment='택배사명(발송방법)'),
    sa.Column('sale_method', sa.String(length=50), nullable=True, comment='판매방식'),
    sa.Column('order_etc_7', sa.String(length=200), nullable=True, comment='판매자 관리코드'),
    sa.Column('sale_coupon', sa.Numeric(precision=15, scale=2), nullable=True, comment='판매자쿠폰할인'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smile_macro')
    # ### end Alembic commands ###
