"""0911a_order_erp_nullable

Revision ID: bd10cae64be5
Revises: e81654a38fd5
Create Date: 2025-09-11 06:47:24.437460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd10cae64be5'
down_revision: Union[str, None] = 'e81654a38fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecount_purchase', 'exchange_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_comment='통화')
    op.alter_column('ecount_sale', 'exchange_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_comment='통화')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecount_sale', 'exchange_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_comment='통화')
    op.alter_column('ecount_purchase', 'exchange_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_comment='통화')
    # ### end Alembic commands ###
