"""updata data type receive_order and down_from_order

Revision ID: c26b8500c811
Revises: 9974cd4a0062
Create Date: 2025-08-23 07:53:36.160011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26b8500c811'
down_revision: Union[str, None] = '9974cd4a0062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('down_form_orders', 'receive_cel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('down_form_orders', 'receive_tel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('receive_orders', 'receive_tel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('receive_orders', 'receive_cel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('test_down_form_orders', 'receive_cel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('test_down_form_orders', 'receive_tel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_down_form_orders', 'receive_tel',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('test_down_form_orders', 'receive_cel',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('receive_orders', 'receive_cel',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('receive_orders', 'receive_tel',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('down_form_orders', 'receive_tel',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('down_form_orders', 'receive_cel',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
