"""0909a_order_erp_sale_and_purchase_modified

Revision ID: dcb6dba28ee6
Revises: a31b8d3efed2
Create Date: 2025-09-09 06:23:48.007997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb6dba28ee6'
down_revision: Union[str, None] = 'a31b8d3efed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecount_purchase', sa.Column('size_des', sa.String(length=100), nullable=True, comment='규격'))
    op.add_column('ecount_purchase', sa.Column('supply_amt_f', sa.Numeric(precision=28, scale=10), nullable=True, comment='외화금액'))
    op.drop_column('ecount_purchase', 'exchange_cost')
    op.add_column('ecount_sale', sa.Column('supply_amt_f', sa.Numeric(precision=28, scale=10), nullable=True, comment='외화금액'))
    op.drop_column('ecount_sale', 'exchange_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecount_sale', sa.Column('exchange_cost', sa.NUMERIC(precision=28, scale=10), autoincrement=False, nullable=True, comment='외화금액'))
    op.drop_column('ecount_sale', 'supply_amt_f')
    op.add_column('ecount_purchase', sa.Column('exchange_cost', sa.NUMERIC(precision=28, scale=10), autoincrement=False, nullable=True, comment='외화금액'))
    op.drop_column('ecount_purchase', 'supply_amt_f')
    op.drop_column('ecount_purchase', 'size_des')
    # ### end Alembic commands ###
