"""0910a_order_ecount_erp_upload_qty_float_to_int

Revision ID: e81654a38fd5
Revises: dcb6dba28ee6
Create Date: 2025-09-10 07:11:25.276181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81654a38fd5'
down_revision: Union[str, None] = 'dcb6dba28ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecount_purchase', 'qty',
               existing_type=sa.NUMERIC(precision=28, scale=10),
               type_=sa.Numeric(precision=28, scale=0),
               existing_comment='수량',
               existing_nullable=False)
    op.alter_column('ecount_sale', 'qty',
               existing_type=sa.NUMERIC(precision=28, scale=10),
               type_=sa.Numeric(precision=28, scale=0),
               existing_comment='수량',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecount_sale', 'qty',
               existing_type=sa.Numeric(precision=28, scale=0),
               type_=sa.NUMERIC(precision=28, scale=10),
               existing_comment='수량',
               existing_nullable=False)
    op.alter_column('ecount_purchase', 'qty',
               existing_type=sa.Numeric(precision=28, scale=0),
               type_=sa.NUMERIC(precision=28, scale=10),
               existing_comment='수량',
               existing_nullable=False)
    # ### end Alembic commands ###
