"""0820b_smile_macro,down_form_order-modified_for_order_integration_1st_data

Revision ID: f35a4bad392d
Revises: bc201165454f
Create Date: 2025-08-21 03:10:42.836724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35a4bad392d'
down_revision: Union[str, None] = 'bc201165454f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smile_macro', sa.Column('sku_value', sa.String(length=200), nullable=True, comment='주문옵션'))
    op.drop_column('smile_macro', 'chat_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smile_macro', sa.Column('chat_1', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='주문옵션'))
    op.drop_column('smile_macro', 'sku_value')
    # ### end Alembic commands ###
