"""0928b_product_mall_value_table_added

Revision ID: f7a6426e65ad
Revises: 069694b2a301
Create Date: 2025-09-28 09:48:41.445556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a6426e65ad'
down_revision: Union[str, None] = '069694b2a301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_mall_value',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_nm', sa.String(length=100), nullable=True),
    sa.Column('standard_price', sa.Integer(), nullable=True),
    sa.Column('compayny_goods_cd', sa.String(length=100), nullable=True),
    sa.Column('test_product_raw_data_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('gubun', sa.String(length=50), nullable=True),
    sa.Column('mall_prod_name', sa.String(length=200), nullable=True),
    sa.Column('mall_prop1_cd', sa.String(length=100), nullable=True),
    sa.Column('buinf_id3', sa.String(length=100), nullable=True),
    sa.Column('mall_stock_rate', sa.String(length=50), nullable=True),
    sa.Column('certno', sa.String(length=100), nullable=True),
    sa.Column('issuedate', sa.String(length=50), nullable=True),
    sa.Column('certdate', sa.String(length=50), nullable=True),
    sa.Column('avlst_dm', sa.String(length=50), nullable=True),
    sa.Column('avled_dm', sa.String(length=50), nullable=True),
    sa.Column('cert_agency', sa.String(length=100), nullable=True),
    sa.Column('certfield', sa.String(length=100), nullable=True),
    sa.Column('shop0007', sa.Integer(), nullable=True),
    sa.Column('shop0042', sa.Integer(), nullable=True),
    sa.Column('shop0087', sa.Integer(), nullable=True),
    sa.Column('shop0094', sa.Integer(), nullable=True),
    sa.Column('shop0121', sa.Integer(), nullable=True),
    sa.Column('shop0129', sa.Integer(), nullable=True),
    sa.Column('shop0154', sa.Integer(), nullable=True),
    sa.Column('shop0650', sa.Integer(), nullable=True),
    sa.Column('shop0029', sa.Integer(), nullable=True),
    sa.Column('shop0189', sa.Integer(), nullable=True),
    sa.Column('shop0322', sa.Integer(), nullable=True),
    sa.Column('shop0444', sa.Integer(), nullable=True),
    sa.Column('shop0100', sa.Integer(), nullable=True),
    sa.Column('shop0298', sa.Integer(), nullable=True),
    sa.Column('shop0372', sa.Integer(), nullable=True),
    sa.Column('shop0381', sa.Integer(), nullable=True),
    sa.Column('shop0416', sa.Integer(), nullable=True),
    sa.Column('shop0449', sa.Integer(), nullable=True),
    sa.Column('shop0498', sa.Integer(), nullable=True),
    sa.Column('shop0583', sa.Integer(), nullable=True),
    sa.Column('shop0587', sa.Integer(), nullable=True),
    sa.Column('shop0661', sa.Integer(), nullable=True),
    sa.Column('shop0055', sa.Integer(), nullable=True),
    sa.Column('shop0067', sa.Integer(), nullable=True),
    sa.Column('shop0068', sa.Integer(), nullable=True),
    sa.Column('shop0273', sa.Integer(), nullable=True),
    sa.Column('shop0464', sa.Integer(), nullable=True),
    sa.Column('shop0075', sa.Integer(), nullable=True),
    sa.Column('shop0319', sa.Integer(), nullable=True),
    sa.Column('shop0365', sa.Integer(), nullable=True),
    sa.Column('shop0387', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_mall_value')
    # ### end Alembic commands ###
