from typing import Any
from decimal import Decimal
from datetime import datetime


EXPORT_FORM_ORDERS: list[dict[str, Any]] = [
    {
        "id": 1,
        "process_dt": datetime.now(),
        "form_name": "내보내기폼1",
        "seq": 1,
        "idx": "EXPORT_ORDER001",
        "order_id": "MALL_EXPORT_ORDER001",
        "mall_order_id": "MALL_EXPORT_ORDER001",
        "product_id": "PRODUCT001",
        "product_name": "테스트상품1",
        "mall_product_id": "MALL_PRODUCT001",
        "item_name": "상품명1",
        "sku_value": "빨강,S",
        "sku_alias": "SKU별칭1",
        "sku_no": "SKU001",
        "barcode": "1234567890123",
        "model_name": "MODEL001",
        "erp_model_name": "ERP_MODEL001",
        "location_nm": "위치1",
        "sale_cnt": 1,
        "pay_cost": Decimal("12000"),
        "delv_cost": Decimal("3000"),
        "total_cost": Decimal("15000"),
        "total_delv_cost": Decimal("3000"),
        "expected_payout": Decimal("10000"),
        "etc_cost": "기타비용",
        "price_formula": "가격공식1",
        "service_fee": Decimal("1000"),
        "sum_p_ea": Decimal("12000"),
        "sum_expected_payout": Decimal("10000"),
        "sum_pay_cost": Decimal("12000"),
        "sum_delv_cost": Decimal("3000"),
        "sum_total_cost": Decimal("15000"),
        "receive_name": "홍길동",
        "receive_cel": "010-1234-5678",
        "receive_tel": "02-1234-5678",
        "receive_addr": "서울시 강남구 테스트로 123",
        "receive_zipcode": "12345",
        "delivery_payment_type": "선결제",
        "delv_msg": "배송메시지",
        "delivery_id": "DELIVERY001",
        "delivery_class": "일반배송",
        "free_gift": "사은품",
        "etc_msg": "기타메시지",
        "order_etc_7": "주문기타7",
        "invoice_no": "INVOICE001",
        "fld_dsp": "필드설명",
        "order_etc_6": "주문기타6",
        "order_date": datetime.now(),
        "reg_date": "20240101120000",
        "ord_confirm_date": "20240101130000",
        "rtn_dt": None,
        "chng_dt": None,
        "delivery_confirm_date": "20240101140000",
        "cancel_dt": None,
        "hope_delv_date": "20240103",
        "inv_send_dm": "20240101150000"
    },
    {
        "id": 2,
        "process_dt": datetime.now(),
        "form_name": "내보내기폼2",
        "seq": 2,
        "idx": "EXPORT_ORDER002",
        "order_id": "MALL_EXPORT_ORDER002",
        "mall_order_id": "MALL_EXPORT_ORDER002",
        "product_id": "PRODUCT002",
        "product_name": "테스트상품2",
        "mall_product_id": "MALL_PRODUCT002",
        "item_name": "상품명2",
        "sku_value": "검정,M",
        "sku_alias": "SKU별칭2",
        "sku_no": "SKU002",
        "barcode": "1234567890124",
        "model_name": "MODEL002",
        "erp_model_name": "ERP_MODEL002",
        "location_nm": "위치2",
        "sale_cnt": 2,
        "pay_cost": Decimal("20000"),
        "delv_cost": Decimal("3000"),
        "total_cost": Decimal("23000"),
        "total_delv_cost": Decimal("3000"),
        "expected_payout": Decimal("18000"),
        "etc_cost": "기타비용2",
        "price_formula": "가격공식2",
        "service_fee": Decimal("1500"),
        "sum_p_ea": Decimal("20000"),
        "sum_expected_payout": Decimal("18000"),
        "sum_pay_cost": Decimal("20000"),
        "sum_delv_cost": Decimal("3000"),
        "sum_total_cost": Decimal("23000"),
        "receive_name": "김철수",
        "receive_cel": "010-2345-6789",
        "receive_tel": "02-2345-6789",
        "receive_addr": "서울시 서초구 테스트로 456",
        "receive_zipcode": "23456",
        "delivery_payment_type": "선결제",
        "delv_msg": "배송메시지2",
        "delivery_id": "DELIVERY002",
        "delivery_class": "일반배송",
        "free_gift": "사은품2",
        "etc_msg": "기타메시지2",
        "order_etc_7": "주문기타7-2",
        "invoice_no": "INVOICE002",
        "fld_dsp": "필드설명2",
        "order_etc_6": "주문기타6-2",
        "order_date": datetime.now(),
        "reg_date": "20240102120000",
        "ord_confirm_date": "20240102130000",
        "rtn_dt": None,
        "chng_dt": None,
        "delivery_confirm_date": None,
        "cancel_dt": None,
        "hope_delv_date": "20240104",
        "inv_send_dm": "20240102150000"
    }
] 